### ISSUE TITLE
Make it work w/ elm-reactor

### ISSUE THREAD

**Issue by avh4** [elmbridge/elmoji-translator#3]
I used a trick in https://github.com/elmbridge/intro-to-elm-part-1 to add references to external CSS  using elm-html without needed a custom html file.  If we do something similar here, we could then use `elm-reactor` and avoid the students having to re-run `elm-make` all the time.

**Comment by raorao** [comment]
:heart: :heart: :heart:

**Comment by raorao** [comment]
I wonder if it's worth getting students to manually compile, to make it all feel less magical. That said, some magic might be fine in a 1-day tutorial.

**Comment by raorao** [comment]
elm-reactor also makes deployment harder. 

On second thought, I think I'd like to push students to use a tool like `rerun` or `watch` or `entr` -- something they control so there's less magic floating around. Still mulling it over though.

**Comment by avh4** [comment]
(Deployment with elm-reactor would be 'elm-make Main.elm' and then publish
the index.html file)

**Comment by avh4** [comment]
Personally, I think elm-reactor is less magical than rerun/watch/etc

**Comment by eeue56** [comment]
the main magic for elm-reactor comes from injection of stylesheets and fonts

**Comment by avh4** [comment]
I got it working here:  https://github.com/elmbridge/elmoji-translator/compare/05b19ede8c27afc843523ff158551c29b86c166f...a7a1198b0e7f19dddf424f0e3d4cc1a743aed2c8  (There's no good way to make a PR, because of how we're using tags in the repo...

that branch works with elm-reactor, and `elm-make Main.elm` also produces an index.html that works equally well (for publishing).

Lmk if there are any concerns.  I'll start a branch on the curriculum repo for the necessary content updates.

**Comment by avh4** [comment]
Fixed in a7a1198b0e7f19dddf424f0e3d4cc1a743aed2c8
