### ISSUE TITLE
Rename "model.text" in the hello-world branch

### ISSUE THREAD

**Issue by avh4** [elmbridge/elmoji-translator#4]
In the starting-point for the afternoon part of the curriculum, the model has a field called `text`, which is perhaps confusing because the curriculum also talks about `Html.text` in the same section.

I propose renaming the field in the model to something else.

**Comment by raorao** [comment]
good catch.

**Comment by avh4** [comment]
Fixed in 500358d3d123109bc30a7eb842b419b7c2a0f145
